"""Reusable X-ray diffraction analysis toolkit for electroceramics research."""

from importlib.metadata import PackageNotFoundError, version

from xrdkit.broadening import (
    BreadthModelFit,
    BreadthModels,
    BroadeningCorrection,
    Caglioti,
    ProfileFit,
    correct_broadening,
    doublet_gaps,
    fit_breadth_models,
    fit_caglioti,
    fit_profile,
    height_spread_breadth,
    integral_breadth,
    kalpha2_position,
    pseudo_voigt,
    pseudo_voigt_components,
    pseudo_voigt_from_components,
    split_pseudo_voigt,
)
from xrdkit.cell import Cell
from xrdkit.config import (
    ConfigError,
    check_composition,
    load_config,
    sample_settings,
    validate_config,
    wyckoff_multiplicity,
)
from xrdkit.density import (
    ATOMIC_MASSES,
    cell_volume,
    formula_mass,
    parse_formula,
    relative_density,
    theoretical_density,
)
from xrdkit.gsas2 import (
    Gsas2Error,
    Gsas2Install,
    accepted_stages,
    build_refine_job,
    failure_markdown,
    find_gsas2,
    gsas2_fwhm,
    log_tail,
    run_job,
    stage_status,
    stage_status_table,
    stage_statuses,
    standard_stages,
    structure_edits,
    summary_markdown,
    write_instprm,
)
from xrdkit.indexing import (
    TTB_CELL,
    CellFit,
    IndexedPeak,
    Reflection,
    TetragonalCell,
    ZeroSearch,
    estimate_zero_offset,
    generate_reflections,
    index_and_refine,
    index_peaks,
    indexed_to_csv,
    indexing_summary,
    refine_cell,
)
from xrdkit.io import XRDScan, read_xrdml
from xrdkit.lattice import LatticeFit, lattice_fit_to_dict, refine_lattice
from xrdkit.library import Site, StructureEntry, list_entries, load_entry
from xrdkit.peaks import (
    Peak,
    exclude_kalpha2,
    find_peaks,
    flag_kalpha2,
    peaks_to_csv,
)
from xrdkit.phases import (
    CandidateMatch,
    CodRecord,
    ExplainedPeak,
    SimulatedReflection,
    cod_fetch,
    cod_search,
    match_candidate,
    simulate_pattern,
    write_cif_index,
)
from xrdkit.plotting import (
    annotate_hkl,
    apply_style,
    mark_peaks,
    plot_caglioti,
    plot_pattern,
    plot_rietveld,
    plot_stacked,
    save_figure,
)
from xrdkit.project import Project, find_project, load_project
from xrdkit.quality import ScanQuality, assess_scan, format_report
from xrdkit.sizestrain import (
    ComponentSizeStrain,
    ResolutionLimit,
    WilliamsonHall,
    component_size_strain,
    resolution_limit,
    scherrer_size,
    scherrer_size_integral,
    williamson_hall,
)
from xrdkit.structure import (
    Distance,
    bond_lengths,
    cell_contents,
    composition_edits,
    interatomic_distances,
    metric_tensor,
    site_setup,
)
from xrdkit.symmetry import (
    holohedry,
    is_absent,
    laue_group,
    laue_orbit,
    multiplicity,
    parse_xyz,
    representative,
    space_group_operations,
)

try:
    __version__ = version("xrdkit")
except PackageNotFoundError:  # running from a source tree, not installed
    __version__ = "0.0.0+unknown"

__all__ = [
    "ATOMIC_MASSES",
    "TTB_CELL",
    "BreadthModelFit",
    "BreadthModels",
    "BroadeningCorrection",
    "Caglioti",
    "CandidateMatch",
    "Cell",
    "CellFit",
    "CodRecord",
    "ComponentSizeStrain",
    "ConfigError",
    "Distance",
    "ExplainedPeak",
    "Gsas2Error",
    "Gsas2Install",
    "IndexedPeak",
    "LatticeFit",
    "Peak",
    "ProfileFit",
    "Project",
    "Reflection",
    "ResolutionLimit",
    "ScanQuality",
    "SimulatedReflection",
    "Site",
    "StructureEntry",
    "TetragonalCell",
    "WilliamsonHall",
    "XRDScan",
    "ZeroSearch",
    "__version__",
    "accepted_stages",
    "annotate_hkl",
    "apply_style",
    "assess_scan",
    "bond_lengths",
    "build_refine_job",
    "cell_contents",
    "cell_volume",
    "check_composition",
    "cod_fetch",
    "cod_search",
    "component_size_strain",
    "composition_edits",
    "correct_broadening",
    "doublet_gaps",
    "estimate_zero_offset",
    "exclude_kalpha2",
    "failure_markdown",
    "find_gsas2",
    "find_peaks",
    "find_project",
    "fit_breadth_models",
    "fit_caglioti",
    "fit_profile",
    "flag_kalpha2",
    "format_report",
    "formula_mass",
    "generate_reflections",
    "gsas2_fwhm",
    "height_spread_breadth",
    "holohedry",
    "index_and_refine",
    "index_peaks",
    "indexed_to_csv",
    "indexing_summary",
    "integral_breadth",
    "interatomic_distances",
    "is_absent",
    "kalpha2_position",
    "lattice_fit_to_dict",
    "laue_group",
    "laue_orbit",
    "list_entries",
    "load_config",
    "load_entry",
    "load_project",
    "log_tail",
    "mark_peaks",
    "match_candidate",
    "metric_tensor",
    "multiplicity",
    "parse_formula",
    "parse_xyz",
    "peaks_to_csv",
    "plot_caglioti",
    "plot_pattern",
    "plot_rietveld",
    "plot_stacked",
    "pseudo_voigt",
    "pseudo_voigt_components",
    "pseudo_voigt_from_components",
    "read_xrdml",
    "refine_cell",
    "refine_lattice",
    "relative_density",
    "representative",
    "resolution_limit",
    "run_job",
    "sample_settings",
    "save_figure",
    "scherrer_size",
    "scherrer_size_integral",
    "simulate_pattern",
    "site_setup",
    "space_group_operations",
    "split_pseudo_voigt",
    "stage_status",
    "stage_status_table",
    "stage_statuses",
    "standard_stages",
    "structure_edits",
    "summary_markdown",
    "theoretical_density",
    "validate_config",
    "williamson_hall",
    "write_cif_index",
    "write_instprm",
    "wyckoff_multiplicity",
]
